app/config/FrontendAppConfig.scala, app/views/GovukWrapper.scala.html, app/views/MainTemplate.scala.html, conf/application.conf, project/plugins.sbt
**New feature**
Google Tag Manager Config Added
=> DL-2528 - GTM Added

build.sbt, project/AppDependencies.scala, project/build.properties, project/plugins.sbt, project/scaffold.sbt, test/models/TaxYearSelectionSpec.scala
- [X ]  I've made every effort to commit high quality, clean code and I have executed relevant static analyses to be sure
=> DL-3520 - Dep. updates & warnings removed

project/AppDependencies.scala
=> DL-5457 - Bootstrap upgrade to 5.3.0

app/views/docks/DocksOccupationList1View.scala.html, test/views/docks/DocksOccupationList1ViewSpec.scala
=> DL-7721: Docks view updated

app/views/electrical/ElectricalView.scala.html, app/views/playComponents/input_radio.scala.html, app/views/playComponents/input_yes_no.scala.html, test/views/MultipleEmploymentsViewSpec.scala, test/views/electrical/ElectricalViewSpec.scala
=> DL-7722: Electrical View

app/views/foodCatering/CateringStaffNHSView.scala.html, test/views/foodCatering/CateringStaffNHSViewSpec.scala
=> DL-7724: cateringStaffNhs view 

app/views/healthcare/AmbulanceStaffView.scala.html, app/views/healthcare/HealthcareList1View.scala.html, app/views/healthcare/HealthcareList2View.scala.html, app/views/playComponents/back_link.scala.html, app/views/playComponents/input_yes_no.scala.html, test/views/healthcare/AmbulanceStaffViewSpec.scala, test/views/healthcare/HealthcareList1ViewSpec.scala, test/views/healthcare/HealthcareList2ViewSpec.scala
=> DL-7725: healthcare views

app/views/heating/HeatingOccupationListView.scala.html, test/views/heating/HeatingOccupationListViewSpec.scala
=> DL-7726: Heating view

app/views/manufacturing/AluminiumApprenticeView.scala.html, app/views/manufacturing/AluminiumOccupationList1View.scala.html, app/views/manufacturing/AluminiumOccupationList2View.scala.html, app/views/manufacturing/AluminiumOccupationList3View.scala.html, app/views/manufacturing/IronApprenticeView.scala.html, app/views/manufacturing/IronMiningListView.scala.html, app/views/manufacturing/IronMiningView.scala.html, app/views/manufacturing/IronSteelOccupationListView.scala.html, app/views/manufacturing/TypeOfManufacturingView.scala.html, app/views/manufacturing/WoodFurnitureOccupationList1View.scala.html, app/views/manufacturing/WoodFurnitureOccupationList2View.scala.html, app/views/manufacturing/WoodFurnitureOccupationList3View.scala.html, app/views/playComponents/back_link.scala.html, test/views/manufacturing/AluminiumApprenticeViewSpec.scala, test/views/manufacturing/AluminiumOccupationList1ViewSpec.scala, test/views/manufacturing/AluminiumOccupationList2ViewSpec.scala, test/views/manufacturing/AluminiumOccupationList3ViewSpec.scala, test/views/manufacturing/IronApprenticeViewSpec.scala, test/views/manufacturing/IronMiningListViewSpec.scala, test/views/manufacturing/IronMiningViewSpec.scala, test/views/manufacturing/IronSteelOccupationListViewSpec.scala, test/views/manufacturing/TypeOfManufacturingViewSpec.scala, test/views/manufacturing/WoodFurnitureOccupationList1ViewSpec.scala, test/views/manufacturing/WoodFurnitureOccupationList2ViewSpec.scala, test/views/manufacturing/WoodFurnitureOccupationList3ViewSpec.scala
=> DL-7727: Manufacturing folder views updated

app/views/playComponents/button_link.scala.html, app/views/police/ClaimByPostOrOnlineView.scala.html, app/views/police/CommunitySupportOfficerView.scala.html, app/views/police/MetropolitanPoliceView.scala.html, app/views/police/PoliceOfficerView.scala.html, app/views/police/SpecialConstableView.scala.html, test/views/police/ClaimByPostOrOnlineViewSpec.scala, test/views/police/CommunitySupportOfficerViewSpec.scala, test/views/police/MetropolitanPoliceViewSpec.scala, test/views/police/PoliceOfficerViewSpec.scala, test/views/police/SpecialConstableViewSpec.scala
=> DL-7728: Police views updated

app/views/printing/PrintingOccupationList1View.scala.html, app/views/printing/PrintingOccupationList2View.scala.html, test/views/printing/PrintingOccupationList1ViewSpec.scala, test/views/printing/PrintingOccupationList2ViewSpec.scala
=> DL-7729: printing views updated

app/views/security/SecurityGuardNHSView.scala.html, test/views/security/SecurityGuardNHSViewSpec.scala
=> DL-7730: security view updated

app/views/shipyard/LabourerView.scala.html, app/views/shipyard/ShipyardApprenticeStoreKeeperView.scala.html, app/views/shipyard/ShipyardOccupationList1View.scala.html, app/views/shipyard/ShipyardOccupationList2View.scala.html, test/views/shipyard/LabourerViewSpec.scala, test/views/shipyard/ShipyardApprenticeStorekeeperViewSpec.scala, test/views/shipyard/ShipyardOccupationList1ViewSpec.scala, test/views/shipyard/ShipyardOccupationList2ViewSpec.scala
=> DL-7731: shipyard folder views updated

app/views/textiles/TextilesOccupationList1View.scala.html, test/views/textiles/TextilesOccupationList1ViewSpec.scala
=> DL-7732: textiles view updated

app/views/CannotClaimExpenseView.scala.html, test/views/CannotClaimExpenseViewSpec.scala
=> DL-7734: cannot claim expense view updated

app/views/transport/AirlineJobListView.scala.html, app/views/transport/CabinCrewView.scala.html, app/views/transport/GarageHandOrCleanerView.scala.html, app/views/transport/TransportCarpenterView.scala.html, app/views/transport/TransportVehicleTradeView.scala.html, app/views/transport/TypeOfTransportView.scala.html, app/views/transport/WhichRailwayTradeView.scala.html, test/views/transport/AirlineJobListViewSpec.scala, test/views/transport/CabinCrewViewSpec.scala, test/views/transport/GarageHandOrCleanerViewSpec.scala, test/views/transport/TransportCarpenterViewSpec.scala, test/views/transport/TransportVehicleTradeViewSpec.scala, test/views/transport/TypeOfTransportViewSpec.scala, test/views/transport/WhichRailwayTradeViewSpec.scala
=> DL-7733: transport views updated

app/views/CannotClaimView.scala.html, test/views/CannotClaimViewSpec.scala
=> DL-7735: CannotClaim view updated

app/views/ClaimAmountView.scala.html, test/views/ClaimAmountViewSpec.scala
=> DL-7736: ClaimAmountView updated

app/views/authenticated/AlreadyClaimingFREDifferentAmountsView.scala.html, app/views/authenticated/AlreadyClaimingFRESameAmountView.scala.html, app/views/authenticated/ChangeWhichTaxYearsView.scala.html, app/views/authenticated/CheckYourAnswersView.scala.html, app/views/authenticated/NoCodeChangeView.scala.html, app/views/authenticated/RemoveFRECodeView.scala.html, app/views/authenticated/TaxYearSelectionView.scala.html, app/views/authenticated/UpdateEmployerInformationView.scala.html, app/views/authenticated/YourEmployerView.scala.html, app/views/playComponents/answer_row.scala.html, app/views/playComponents/answer_section.scala.html, app/views/playComponents/input_checkbox_table.scala.html, app/views/playComponents/input_tax_year.scala.html, app/views/playComponents/repeater_answer_section.scala.html, test/views/authenticated/AlreadyClaimingFREDifferentAmountsViewSpec.scala, test/views/authenticated/AlreadyClaimingFRESameAmountViewSpec.scala, test/views/authenticated/ChangeWhichTaxYearsViewSpec.scala, test/views/authenticated/CheckYourAnswersViewSpec.scala, test/views/authenticated/NoCodeChangeViewSpec.scala, test/views/authenticated/RemoveFRECodeViewSpec.scala, test/views/authenticated/TaxYearSelectionViewSpec.scala, test/views/authenticated/UpdateEmployerInformationViewSpec.scala, test/views/authenticated/YourEmployerViewSpec.scala, test/views/newBehaviours/CheckboxViewBehaviours.scala
=> DL-7717:authenticated folder views updated

app/views/ClaimByAlternativeView.scala.html, test/views/ClaimByAlternativeViewSpec.scala
=> DL-7737: ClaimByAlternative view updated

app/views/ErrorTemplate.scala.html
=> DL-7739: errorTemplate view updated

app/views/EmployerContributionView.scala.html, app/views/MultipleEmploymentsView.scala.html, app/views/authenticated/AlreadyClaimingFREDifferentAmountsView.scala.html, app/views/authenticated/AlreadyClaimingFRESameAmountView.scala.html, app/views/authenticated/RemoveFRECodeView.scala.html, app/views/construction/ConstructionOccupationsView.scala.html, app/views/engineering/AncillaryEngineeringWhichTradeView.scala.html, app/views/engineering/TypeOfEngineeringView.scala.html, app/views/manufacturing/TypeOfManufacturingView.scala.html, app/views/playComponents/input_radio.scala.html, app/views/transport/TransportVehicleTradeView.scala.html, app/views/transport/TypeOfTransportView.scala.html, app/views/transport/WhichRailwayTradeView.scala.html, test/views/EmployerContributionViewSpec.scala
=> DL-7738: EmployerContribution view +spacing updated

app/views/FifthIndustryOptionsView.scala.html, test/views/FifthIndustryOptionsViewSpec.scala
=> DL-7741: FifthIndustry view updated

app/views/FirstIndustryOptionsView.scala.html, test/views/FirstIndustryOptionsViewSpec.scala
=> DL-7742: FirstIndustryOption view updated

app/views/FourthIndustryOptionsView.scala.html, test/views/FourthIndustryOptionsViewSpec.scala
=> DL-7743: FourthIndustry view updated

app/views/SecondIndustryOptionsView.scala.html, test/views/SecondIndustryOptionsViewSpec.scala
=> DL-7751: SecondayIndustry view updated

app/views/ThirdIndustryOptionsView.scala.html, test/views/ThirdIndustryOptionsViewSpec.scala
=> DL-7753: ThirdIndustry view updated

app/views/HowYouWillGetYourExpensesCurrentAndPreviousYearView.scala.html, test/views/HowYouWillGetYourExpensesCurrentAndPreviousYearViewSpec.scala
=> DL-7744 HowYouWillGetYourExpensesCurrentAndPreviousYear view updated

app/views/HowYouWillGetYourExpensesPreviousView.scala.html, test/views/HowYouWillGetYourExpensesPreviousViewSpec.scala
=> DL-7746: Expenses Previous view updated

app/views/IndexView.scala.html, test/views/IndexViewSpec.scala
=> DL-7747: index view updated

app/views/HowYouWillGetYourExpensesCurrentView.scala.html, test/views/HowYouWillGetYourExpensesCurrentViewSpec.scala
=> DL-7745: ExpensesCurrent view updated

app/views/PhoneUsView.scala.html, test/views/PhoneUsViewSpec.scala
=> DL-7749: phoneUs view updated

app/views/SessionExpiredView.scala.html, test/views/SessionExpiredViewSpec.scala
=> DL-7752: sessionExpired view updated

app/views/SameEmployerContributionAllYearsView.scala.html, test/views/SameEmployerContributionAllYearsViewSpec.scala
=> DL-7750: sameEmployer view updated

app/views/UnauthorisedView.scala.html, test/views/UnauthorisedViewSpec.scala
=> DL-7754: UnauthorisedView updated

app/views/authenticated/AlreadyClaimingFREDifferentAmountsView.scala.html, app/views/authenticated/AlreadyClaimingFRESameAmountView.scala.html, app/views/playComponents/confirmation_footer.scala.html
=> DL-8507: link text size and table spacing updated

project/AppDependencies.scala
=> DL-11453 removing http-caching-client

app/views/Layout.scala.html, conf/application.conf
=> DL-11953 swapping form govuklayout to hmrcstandardpage

conf/application.conf, project/AppDependencies.scala, project/plugins.sbt
DL-12131
Updating the "claim by post" and "claim online" links on the **/claim-by-alternative** page
=> DL-12131 Updating links on 'claim by alternative' page

project/AppDependencies.scala
=> DL-12973 Crown update

build.sbt, conf/logback.xml, conf/messages, conf/messages.cy, project/build.properties, project/plugins.sbt
=> DL-14103 Correcting missing title message

app/views/LayoutProvider.scala
=> DL-14140-2 fixed sign out link in header

app/connectors/CitizenDetailsConnector.scala, app/connectors/EmployeeWfhExpensesConnector.scala, app/connectors/TaiConnector.scala, app/handlers/ErrorHandler.scala, app/views/ErrorTemplate.scala.html, app/views/LayoutProvider.scala, app/views/playComponents/AdditionalScript.scala.html, conf/application.conf, project/AppDependencies.scala, project/plugins.sbt, test/controllers/IndexControllerSpec.scala, test/controllers/KeepAliveControllerSpec.scala, test/controllers/actions/DataRequiredActionSpec.scala, test/utils/MockEeFormPartialRetriever.scala
=> DL-14253 Dependency updates

app/config/FrontendAppConfig.scala, app/controllers/authenticated/SignOutController.scala, conf/application.conf, test/controllers/authenticated/SignOutControllerSpec.scala
DL-16366:Signout using bas-gateway
=> DL-16366:Signout using bas-gateway

app/config/FrontendAppConfig.scala, app/controllers/MultipleEmploymentsController.scala, app/navigation/GenericNavigator.scala, build.sbt, conf/application.conf, project/AppDependencies.scala, project/plugins.sbt, test/navigation/GenericNavigatorSpec.scala
=> DL-16432: Updated unit test to match with navigation changes
